;; sample response anonymized from confluence response using plz
(setf sample-response-1 `((results . ,(vector '((id . 123456)
                                                (ari . ari:cloud:confluence:ed2cffd3-8776-47d3-a9ed-21800743bc65:space/123456)
                                                (key . ~123456789abcdef123456789abcdef12345678)
                                                (alias . ~123456789abcdef123456789abcdef12345678)
                                                (name . testuser01)
                                                (type . personal)
                                                (status . current)
                                                (_expandable (settings . /rest/api/space/~123456789abcdef123456789abcdef12345678/settings)
                                                             (metadata . nil)
                                                             (identifiers . nil)
                                                             (roles . nil)
                                                             (icon . nil)
                                                             (typeSettings . nil)
                                                             (description . nil)
                                                             (history . nil)
                                                             (operations . nil)
                                                             (lookAndFeel . /rest/api/settings/lookandfeel?spaceKey=~123456789abcdef123456789abcdef12345678)
                                                             (permissions . nil)
                                                             (theme . /rest/api/space/~123456789abcdef123456789abcdef12345678/theme)
                                                             (homepage . /rest/api/content/567890))
                                                (_links (webui . /spaces/~123456789abcdef123456789abcdef12345678)
                                                        (self . https://exeval.atlassian.net/wiki/rest/api/space/~123456789abcdef123456789abcdef12345678)))
                                              '((id . 234567)
                                                (ari . ari:cloud:confluence:ed2cffd3-8776-47d3-a9ed-21800743bc65:space/234567)
                                                (key . SD)
                                                (alias . SD)
                                                (name . "Software development")
                                                (type . global)
                                                (status . current)
                                                (_expandable (settings . /rest/api/space/SD/settings)
                                                             (metadata . nil)
                                                             (identifiers . nil)
                                                             (roles . nil)
                                                             (icon . nil)
                                                             (typeSettings . nil)
                                                             (description . nil)
                                                             (history . nil)
                                                             (operations . nil)
                                                             (lookAndFeel . /rest/api/settings/lookandfeel?spaceKey=SD)
                                                             (permissions . nil)
                                                             (theme . /rest/api/space/SD/theme)
                                                             (homepage . /rest/api/content/163966))
                                                (_links (webui . /spaces/SD)
                                                        (self . https://exeval.atlassian.net/wiki/rest/api/space/SD)))))
                          (start . 0)
                          (limit . 100)
                          (size . 2)
                          (_links (base . https://fakespace.atlassian.net/wiki)
                                  (context . /wiki)
                                  (self . https://fakespace.atlassian.net/wiki/rest/api/space))))
